import org.j2eebuilder.util.log.LogManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Console {
	public static LogManager logger = LogManager.getLogManager(Console.class);

	public boolean someLibraryMethod() {
		return true;
	}

	public void runCli() {
		String configDir = "/Users/sdixit/Dev/jeebuilder/src/components/fnd/src/test/resources/";
		org.j2eebuilder.statement.Cli.main(new String[] { configDir });
	}

	public static void main(String[] args) {
		// System.out.println("args:" + Arrays.deepToString(args));
		if (args == null || args.length != 1) {
			System.out.println("Usage: java -jar opac-cli-all.jar /path/opac-config.xml");
			return;
		}
		String configDir = args[0].trim();
		try {
			org.j2eebuilder.statement.Cli.main(new String[] { configDir });
		} catch (Exception e) {
			logger.fatal(e);
		}
	}
}
