/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class ConsoleTest {
    @Test public void testSomeLibraryMethod() {
        Console classUnderTest = new Console();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    
//    @Test public void testRunCli() {
//    		Library classUnderTest = new Library();
//    		classUnderTest.runCli();
//    }
}
